# Generated by Django 3.1 on 2023-04-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_auto_20220627_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.FileField(upload_to='documents/')),
                ('lasteat', models.IntegerField()),
            ],
            options={
                'db_table': 'Image_Store',
            },
        ),
        migrations.DeleteModel(
            name='Audio_store',
        ),
    ]
