# Generated by Django 3.1 on 2023-04-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_auto_20230416_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_store',
            old_name='record',
            new_name='left',
        ),
        migrations.AddField(
            model_name='image_store',
            name='right',
            field=models.FileField(default=0, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
